"""Made client email column unique

Revision ID: 0015ce49b8a0
Revises: 0d7c0399d0d7
Create Date: 2019-01-14 13:09:50.779564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0015ce49b8a0'
down_revision = '0d7c0399d0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_email', table_name='client')
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.create_index('ix_client_email', 'client', ['email'], unique=False)
    # ### end Alembic commands ###
