"""Added client id column to Interaction table

Revision ID: 0d7c0399d0d7
Revises: 2e9057bee48d
Create Date: 2019-01-13 20:54:29.738622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7c0399d0d7'
down_revision = '2e9057bee48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_interaction_client_id'), 'interaction', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_client_id'), table_name='interaction')
    op.drop_column('interaction', 'client_id')
    # ### end Alembic commands ###
