"""removed index params

Revision ID: 13ba4f9fa9a5
Revises: ea3c63115233
Create Date: 2019-01-21 01:32:41.910549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ba4f9fa9a5'
down_revision = 'ea3c63115233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interaction_about', table_name='interaction')
    op.drop_index('ix_interaction_date', table_name='interaction')
    op.drop_index('ix_interaction_marketer', table_name='interaction')
    op.drop_index('ix_interaction_time', table_name='interaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_interaction_time', 'interaction', ['time'], unique=False)
    op.create_index('ix_interaction_marketer', 'interaction', ['marketer'], unique=False)
    op.create_index('ix_interaction_date', 'interaction', ['date'], unique=False)
    op.create_index('ix_interaction_about', 'interaction', ['about'], unique=False)
    # ### end Alembic commands ###
