"""empty message

Revision ID: 19aae46488dc
Revises: d2a5b580f710
Create Date: 2018-11-08 21:48:55.730150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19aae46488dc'
down_revision = 'd2a5b580f710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memo_author'), 'memo', ['author'], unique=False)
    op.create_index(op.f('ix_memo_date'), 'memo', ['date'], unique=False)
    op.drop_index('ix_message_board_author', table_name='message_board')
    op.drop_index('ix_message_board_date', table_name='message_board')
    op.drop_table('message_board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_board',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='message_board_pkey')
    )
    op.create_index('ix_message_board_date', 'message_board', ['date'], unique=False)
    op.create_index('ix_message_board_author', 'message_board', ['author'], unique=False)
    op.drop_index(op.f('ix_memo_date'), table_name='memo')
    op.drop_index(op.f('ix_memo_author'), table_name='memo')
    op.drop_table('memo')
    # ### end Alembic commands ###
