"""Interaction table

Revision ID: 2e9057bee48d
Revises: 4462a7a5b785
Create Date: 2019-01-13 20:34:57.592654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9057bee48d'
down_revision = '4462a7a5b785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketer', sa.String(length=30), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('time', sa.String(length=30), nullable=True),
    sa.Column('type_of', sa.String(length=30), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_about'), 'interaction', ['about'], unique=False)
    op.create_index(op.f('ix_interaction_date'), 'interaction', ['date'], unique=False)
    op.create_index(op.f('ix_interaction_marketer'), 'interaction', ['marketer'], unique=False)
    op.create_index(op.f('ix_interaction_time'), 'interaction', ['time'], unique=False)
    op.create_index(op.f('ix_interaction_type_of'), 'interaction', ['type_of'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_type_of'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_time'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_marketer'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_date'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_about'), table_name='interaction')
    op.drop_table('interaction')
    # ### end Alembic commands ###
