"""empty message

Revision ID: 4462a7a5b785
Revises: d2059e76abcf
Create Date: 2018-11-13 13:31:45.445523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4462a7a5b785'
down_revision = 'd2059e76abcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('signup_date', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_client_signup_date'), 'client', ['signup_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_signup_date'), table_name='client')
    op.drop_column('client', 'signup_date')
    # ### end Alembic commands ###
