"""empty message

Revision ID: 47f183feb454
Revises: 
Create Date: 2018-11-08 11:59:20.949953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f183feb454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_board_author'), 'message_board', ['author'], unique=False)
    op.create_index(op.f('ix_message_board_date'), 'message_board', ['date'], unique=False)
    op.create_index(op.f('ix_message_board_time'), 'message_board', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_board_time'), table_name='message_board')
    op.drop_index(op.f('ix_message_board_date'), table_name='message_board')
    op.drop_index(op.f('ix_message_board_author'), table_name='message_board')
    op.drop_table('message_board')
    # ### end Alembic commands ###
