"""test

Revision ID: 4f2ce05045cc
Revises: 70bce31e0741
Create Date: 2019-01-21 12:23:02.907258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2ce05045cc'
down_revision = '70bce31e0741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interaction_client_id', table_name='interaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_interaction_client_id', 'interaction', ['client_id'], unique=False)
    # ### end Alembic commands ###
