"""test

Revision ID: 70bce31e0741
Revises: e9bc3f906469
Create Date: 2019-01-21 11:35:38.272325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bce31e0741'
down_revision = 'e9bc3f906469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interaction_client_id'), 'interaction', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_client_id'), table_name='interaction')
    # ### end Alembic commands ###
