"""test

Revision ID: 7b2155745066
Revises: 222cfff3ae90
Create Date: 2019-01-21 01:40:49.205208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2155745066'
down_revision = '222cfff3ae90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interaction_client_id'), 'interaction', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_client_id'), table_name='interaction')
    # ### end Alembic commands ###
