"""empty message

Revision ID: b17a2c946b06
Revises: 297c5bafc64c
Create Date: 2018-11-09 10:26:58.881824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17a2c946b06'
down_revision = '297c5bafc64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_email', table_name='client')
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.create_index('ix_client_email', 'client', ['email'], unique=True)
    # ### end Alembic commands ###
