"""empty message

Revision ID: cdea020eafd4
Revises: 47f183feb454
Create Date: 2018-11-08 13:39:59.331507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdea020eafd4'
down_revision = '47f183feb454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_board', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_message_board_timestamp'), 'message_board', ['timestamp'], unique=False)
    op.drop_index('ix_message_board_date', table_name='message_board')
    op.drop_index('ix_message_board_time', table_name='message_board')
    op.drop_column('message_board', 'time')
    op.drop_column('message_board', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_board', sa.Column('date', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('message_board', sa.Column('time', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_message_board_time', 'message_board', ['time'], unique=False)
    op.create_index('ix_message_board_date', 'message_board', ['date'], unique=False)
    op.drop_index(op.f('ix_message_board_timestamp'), table_name='message_board')
    op.drop_column('message_board', 'timestamp')
    # ### end Alembic commands ###
