"""empty message

Revision ID: d2059e76abcf
Revises: b17a2c946b06
Create Date: 2018-11-13 11:10:12.293325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2059e76abcf'
down_revision = 'b17a2c946b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'client_id')
    # ### end Alembic commands ###
