"""empty message

Revision ID: d2a5b580f710
Revises: cdea020eafd4
Create Date: 2018-11-08 14:17:14.957088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2a5b580f710'
down_revision = 'cdea020eafd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_board', sa.Column('date', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_message_board_date'), 'message_board', ['date'], unique=False)
    op.drop_index('ix_message_board_timestamp', table_name='message_board')
    op.drop_column('message_board', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_board', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_message_board_timestamp', 'message_board', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_message_board_date'), table_name='message_board')
    op.drop_column('message_board', 'date')
    # ### end Alembic commands ###
