"""test

Revision ID: e9bc3f906469
Revises: 7b2155745066
Create Date: 2019-01-21 02:09:10.762923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bc3f906469'
down_revision = '7b2155745066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interaction_client_id', table_name='interaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_interaction_client_id', 'interaction', ['client_id'], unique=False)
    # ### end Alembic commands ###
