"""added status column to client table

Revision ID: ea3c63115233
Revises: 0015ce49b8a0
Create Date: 2019-01-18 20:49:56.455710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3c63115233'
down_revision = '0015ce49b8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'status')
    # ### end Alembic commands ###
